
GET http://localhost:3000/setupdb

###

PUT http://localhost:3000/book/jerry123@gmail.com
Content-Type: application/json

{
    "movieId":2002,
    "noOfTickets":2
}

###

GET http://localhost:3000/bookings/jerry123@gmail.com

###

GET http://localhost:3000/movies

###
GET http://localhost:3000/movie/1004

###
POST http://localhost:3000/about-us